/*****************************************
* Constants too large to be in editor.js
*****************************************/

const languages =
    [
        'APL',
        'Asciiarmor',
        'ASN.1',
        'Asterisk',
        'Brainfuck',
        'CLike',
        'Clojure',
        'CMake',
        'Cobol',
        'Coffeescript',
        'CommonLisp',
        'Crystal',
        'CSS',
        'Cypher',
        'D',
        'Dart',
        'Diff',
        'Django',
        'Dockerfile',
        'DTD',
        'Dylan',
        'Ebnf',
        'ECL',
        'Eiffel',
        'Elm',
        'Erlang',
        'Factor',
        'FCL',
        'Forth',
        'Fortran',
        'GAS',
        'GFM',
        'Gherkin',
        'Go',
        'Groovy',
        'Haml',
        'Handlebars',
        'Haskell',
        'Haskell-literate',
        'Haxe',
        'HTMLEmbedded',
        'HTMLMixed',
        'HTTP',
        'IDL',
        'Javascript',
        'Jinja2',
        'JSX',
        'Julia',
        'Livescript',
        'Lua',
        'Markdown',
        'Mathematica',
        'Mbox',
        'mIRC',
        'MLLike',
        'Modelica',
        'Mscgen',
        'Mumps',
        'Nginx',
        'Nsis',
        'Ntriples',
        'Octave',
        'Oz',
        'Pascal',
        'PegJS',
        'Perl',
        'PHP',
        'Pig',
        'Powershell',
        'Properties',
        'Protobuf',
        'Pug',
        'Puppet',
        'Python',
        'Q',
        'R',
        'RPM',
        'RST',
        'Ruby',
        'Rust',
        'SAS',
        'Sass',
        'Scheme',
        'Shell',
        'Sieve',
        'Slim',
        'Smalltalk',
        'Smarty',
        'Solr',
        'Soy',
        'SPARQL',
        'Spreadsheet',
        'SQL',
        'sTeX',
        'Stylus',
        'Swift',
        'Tcl',
        'Text',
        'Textile',
        'Tiddlywiki',
        'Tiki',
        'TOML',
        'Tornado',
        'Troff',
        'TTCN',
        'TTCN-cfg',
        'Turtle',
        'Twig',
        'VB',
        'VBScript',
        'Velocity',
        'Verilog',
        'VHDL',
        'Vue',
        'WebIDL',
        'XML',
        'XQuery',
        'Yacas',
        'YAML',
        'YAML-frontmatter',
        'Z80'
    ];

const language_detection =
    {        "4CS"                       : "CMake",        "6502 ACME Cross Assembler" : "Z80",        "6502 Kick Assembler"       : "Z80",        "6502 TASM/64TASS"          : "Z80",        "ABAP"                      : "",        "ActionScript"              : "",        "ActionScript 3"            : "",        "Ada"                       : "CLike",        "AIMMS"                     : "",        "ALGOL 68"                  : "ECL",        "Apache Log"                : "",        "AppleScript"               : "APL",        "APT Sources"               : "",        "ARM"                       : "GAS",        "ASM (NASM)"                : "GAS",        "ASP"                       : "",        "Asymptote"                 : "",        "autoconf"                  : "",        "Autohotkey"                : "",        "AutoIt"                    : "",        "Avisynth"                  : "",        "Awk"                       : "",        "BASCOM AVR"                : "",        "Bash"                      : "Shell",        "Basic4GL"                  : "",        "Batch"                     : "Shell",        "BibTeX"                    : "",        "Blitz Basic"               : "",        "Blitz3D"                   : "",        "BlitzMax"                  : "",        "BNF"                       : "",        "BOO"                       : "",        "BrainFuck"                 : "Brainfuck",        "C"                         : "CLike",        "C (WinAPI)"                : "CLike",        "C for Macs"                : "CLike",        "C Intermediate Language"   : "CLike",        "C#"                        : "CLike",        "C++"                       : "CLike",        "C++ (WinAPI)"              : "CLike",        "C++ (with Qt extensions)"  : "CLike",        "C: Loadrunner"             : "CLike",        "CAD DCL"                   : "",        "CAD Lisp"                  : "CommonLisp",        "Ceylon"                    : "",        "CFDG"                      : "",        "ChaiScript"                : "",        "Chapel"                    : "",        "Clojure"                   : "Clojure",        "Clone C"                   : "CLike",        "Clone C++"                 : "CLike",        "CMake"                     : "CMake",        "COBOL"                     : "Cobol",        "CoffeeScript"              : "Coffeescript",        "ColdFusion"                : "",        "CSS"                       : "CSS",        "Cuesheet"                  : "",        "D"                         : "D",        "Dart"                      : "Dart",        "DCL"                       : "",        "DCPU-16"                   : "",        "DCS"                       : "",        "Delphi"                    : "",        "Delphi Prism (Oxygene)"    : "",        "Diff"                      : "Diff",        "DIV"                       : "",        "DOT"                       : "",        "E"                         : "",        "Easytrieve"                : "",        "ECMAScript"                : "",        "Eiffel"                    : "Eiffel",        "Email"                     : "",        "EPC"                       : "",        "Erlang"                    : "Erlang",        "Euphoria"                  : "",        "F#"                        : "",        "Falcon"                    : "",        "Filemaker"                 : "",        "FO Language"               : "",        "Formula One"               : "",        "Fortran"                   : "Fortran",        "FreeBasic"                 : "",        "FreeSWITCH"                : "",        "GAMBAS"                    : "",        "Game Maker"                : "",        "GDB"                       : "",        "Genero"                    : "",        "Genie"                     : "",        "GetText"                   : "",        "Go"                        : "Go",        "Groovy"                    : "Groovy",        "GwBasic"                   : "",        "Haskell"                   : "Haskell",        "Haxe"                      : "Haxe",        "HicEst"                    : "",        "HQ9 Plus"                  : "",        "HTML"                      : "HTMLMixed",        "HTML 5"                    : "HTMLMixed",        "Icon"                      : "",        "IDL"                       : "IDL",        "INI file"                  : "",        "Inno Script"               : "",        "INTERCAL"                  : "",        "IO"                        : "",        "ISPF Panel Definition"     : "",        "J"                         : "",        "Java"                      : "CLike",        "Java 5"                    : "CLike",        "JavaScript"                : "Javascript",        "JCL"                       : "",        "jQuery"                    : "Javascript",        "JSON"                      : "Javascript",        "Julia"                     : "Julia",        "KiXtart"                   : "",        "Kotlin"                    : "CLike",        "Latex"                     : "",        "LDIF"                      : "",        "Liberty BASIC"             : "",        "Linden Scripting"          : "",        "Lisp"                      : "CommonLisp",        "LLVM"                      : "",        "Loco Basic"                : "",        "Logtalk"                   : "",        "LOL Code"                  : "",        "Lotus Formulas"            : "",        "Lotus Script"              : "",        "LScript"                   : "",        "Lua"                       : "Lua",        "M68000 Assembler"          : "",        "MagikSF"                   : "",        "Make"                      : "",        "MapBasic"                  : "",        "Markdown"                  : "Markdown",        "MatLab"                    : "Mathematica",        "mIRC"                      : "mIRC",        "MIX Assembler"             : "",        "Modula 2"                  : "",        "Modula 3"                  : "",        "Motorola 68000 HiSoft Dev" : "",        "MPASM"                     : "",        "MXML"                      : "",        "MySQL"                     : "SQL",        "Nagios"                    : "",        "NetRexx"                   : "",        "newLISP"                   : "CommonLisp",        "Nginx"                     : "Nginx",        "Nimrod"                    : "",        "None"                      : "Text",        "NullSoft Installer"        : "",        "Oberon 2"                  : "",        "Objeck Programming Langua" : "",        "Objective C"               : "CLike",        "OCalm Brief"               : "",        "OCaml"                     : "",        "Octave"                    : "",        "Open Object Rexx"          : "",        "OpenBSD PACKET FILTER"     : "",        "OpenGL Shading"            : "",        "Openoffice BASIC"          : "",        "Oracle 11"                 : "",        "Oracle 8"                  : "",        "Oz"                        : "Oz",        "ParaSail"                  : "",        "PARI/GP"                   : "",        "Pascal"                    : "Pascal",        "Pawn"                      : "",        "PCRE"                      : "",        "Per"                       : "",        "Perl"                      : "Perl",        "Perl 6"                    : "Perl",        "PHP"                       : "PHP",        "PHP Brief"                 : "PHP",        "Pic 16"                    : "",        "Pike"                      : "",        "Pixel Bender"              : "",        "PL/I"                      : "",        "PL/SQL"                    : "SQL",        "PostgreSQL"                : "SQL",        "PostScript"                : "",        "POV-Ray"                   : "",        "Power Shell"               : "Powershell",        "PowerBuilder"              : "",        "ProFTPd"                   : "",        "Progress"                  : "",        "Prolog"                    : "",        "Properties"                : "Properties",        "ProvideX"                  : "",        "Puppet"                    : "",        "PureBasic"                 : "",        "PyCon"                     : "",        "Python"                    : "Python",        "Python for S60"            : "Python",        "q/kdb+"                    : "",        "QBasic"                    : "Q",        "QML"                       : "",        "R"                         : "R",        "Racket"                    : "",        "Rails"                     : "Ruby",        "RBScript"                  : "",        "REBOL"                     : "",        "REG"                       : "",        "Rexx"                      : "",        "Robots"                    : "",        "RPM Spec"                  : "RPM",        "Ruby"                      : "Ruby",        "Ruby Gnuplot"              : "Ruby",        "Rust"                      : "Rust",        "SAS"                       : "SAS",        "Scala"                     : "CLike",        "Scheme"                    : "Scheme",        "Scilab"                    : "",        "SCL"                       : "",        "SdlBasic"                  : "",        "Smalltalk"                 : "Smalltalk",        "Smarty"                    : "Smarty",        "SPARK"                     : "",        "SPARQL"                    : "",        "SQF"                       : "",        "SQL"                       : "SQL",        "StandardML"                : "",        "StoneScript"               : "",        "SuperCollider"             : "",        "Swift"                     : "Swift",        "SystemVerilog"             : "",
        "text"                      : 'Text',        "T-SQL"                     : "SQL",        "TCL"                       : "Tcl",        "Tera Term"                 : "",        "thinBasic"                 : "",        "TypoScript"                : "",        "Unicon"                    : "",        "UnrealScript"              : "",        "UPC"                       : "",        "Urbi"                      : "",        "Vala"                      : "",        "VB.NET"                    : "VB",        "VBScript"                  : "VBscript",        "Vedit"                     : "",        "VeriLog"                   : "Verilog",        "VHDL"                      : "VHDL",        "VIM"                       : "",        "Visual Pro Log"            : "",        "VisualBasic"               : "",        "VisualFoxPro"              : "",        "WhiteSpace"                : "",        "WHOIS"                     : "",        "Winbatch"                  : "Shell",        "XBasic"                    : "",        "XML"                       : "XML",        "Xorg Config"               : "",        "XPP"                       : "",        "YAML"                      : "YAML",        "Z80 Assembler"             : "Z80",        "ZXBasic"                   : ""    };

const themes =
    [
        '3024-day',
        '3024-night',
        'abcdef',
        'ambiance-mobile',
        'ambiance',
        'base16-dark',
        'base16-light',
        'bespin',
        'blackboard',
        'cobalt',
        'colorforth',
        'dracula',
        'duotone-dark',
        'duotone-light',
        'eclipse',
        'elegant',
        'erlang-dark',
        'hopscotch',
        'icecoder',
        'isotope',
        'lesser-dark',
        'liquibyte',
        'material',
        'mbo',
        'mdn-like',
        'midnight',
        'monokai',
        'neat',
        'neo',
        'night',
        'panda-syntax',
        'paraiso-dark',
        'paraiso-light',
        'pastel-on-dark',
        'railscasts',
        'rubyblue',
        'seti',
        'solarized light',
        'solarized dark',
        'the-matrix',
        'tomorrow-night-bright',
        'tomorrow-night-eighties',
        'ttcn',
        'twilight',
        'vibrant-ink',
        'xq-dark',
        'xq-light',
        'yeti',
        'zenburn'
    ];

const fonts =
    [
        'Monospace',
        'Arial',
        'Arial Black',
        'Book Antiqua',
        'Courier New',
        'Georgia',
        'Impact',
        'Lucida Console',
        'Lucida Grande',
        'Lucida Sans Unicode',
        'Palatino Linotype',
        'Tahoma',
        'Times New Roman',
        'Trebuchet MS',
        'Verdana'
    ];

const default_settings =
    {
        default_editor      : false,
        theme               : 'midnight',
        lng                 : 'Text',
        font                : 'Monospace',
        font_size           : 13,
        height              : 500,
        
        autoresize  : true,
        tab_conv    : true,
        tab_width   : 4
    };